version: '3'

services:
  overleaf-registration:
    image: ghcr.io/nixigaj/overleaf-registration
    container_name: overleaf-registration
    environment:
      - CAPTCHA_SERVER_KEY=
      - CAPTCHA_CLIENT_KEY=
      - OL_INSTANCE=
      - OL_ADMIN_EMAIL=
      - OL_ADMIN_PASSWORD=
    ports:
      - "38672:5000"
